### ISSUE TITLE
Repo description is inconsistent with readme

### ISSUE THREAD

**Issue by Wuzzy2** [appgurueu/Model-Creator-v1.3#1]
In the description of this repository on GitHub, it says the license is CC BY-NC while the README says it's CC BY-SA.

**Comment by appgurueu** [comment]
Sorry for that

**Comment by Wuzzy2** [comment]
Still not fixed.
“Repository descripion” is the text below the tabs when you click on “Code”.

Current repo description is:

> Model Creator v1.3 Sourcecode. Licensed under : CC-BY-NC 3.0

Readme says:

> Model Creator v1.3 Sourcecode. Licensed under : CC-BY-SA 3.0
